version: '3'

dotenv: ['.env', 'secrets/.env']

tasks:
  format:
    desc: Format all files in the repository, ignoring any potential hidden folder ".sentinel/"
    cmds:
      - find . -name "*.sentinel" ! -path "./.sentinel" -exec sentinel fmt {} \;