version: '3'

dotenv: ['.env', 'secrets/.env']

tasks:
  format:
    desc: Format all files in the repository, ignoring any potential hidden folder ".sentinel/"
    cmds:
      - find . -name "*.sentinel" ! -path "*/.sentinel" -exec sentinel fmt {} \;
  test-functions:
    desc: Test the functions
    cmds:
      - sentinel test function-tests
  test-functions-verbose:
    desc: Test the functions with verbosity
    cmds:
      - sentinel test -verbose function-tests